#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

source $OPENSHIFT_GEAR_DIR/virtenv/bin/activate

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/manage.py syncdb --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/manage.py syncdb --noinput
python "$OPENSHIFT_REPO_DIR"wsgi/manage.py migrate --noinput

echo "Executing 'python $OPENSHIFT_REPO_DIR/wsgi/manage.py collectstatic --noinput'"
python "$OPENSHIFT_REPO_DIR"wsgi/manage.py collectstatic --noinput
